### ISSUE TITLE
Login page

### ISSUE THREAD

**Issue by EmilyLancietti** [2BOT4U/Bot#15]
User story: A user wants to see a page where he can login

HTD:  The user clicks on the login link, then will be redirected on the login page where he  inserts his credentials. After a successful authentication will be redirected to his profile page

**Comment by EmilyLancietti** [comment]
campi richiesti Email e Password

**Comment by AlessioBazzanella** [comment]
# http://127.0.0.1:3000/api/v1/users/login

Header:
-----------
Content-Type: application/x-www-form-urlencoded

Form:
--------
email, password

Response:
--------------
{
    "data": "WmgHMfUgtrTXGV31azffhwd7HIITHScVnxZKP0ziAwXRYc77ZJQjbbbsrvmdyJ0Yq2yiMIsfnBnZW0IrqZ1yXxAq3JutPq8UJw5zWaxKUIqw2wrKO1LbagNNIJKWJY5DLplD45pdinBILdgDMx1MI8vuEShdkgZ9FQySrhF5GafdSnAynbv7n6nHIj7V",
    "status": "OK",
    "code": 200
}

Il campo data contiene il token di accesso da salvare come id per la sessione da usare per le richieste tramite Bearer token

**Comment by AlessioBazzanella** [comment]
Nel caso in cui l'utente non esista:

{
    "data": {
        "message": "Utente non registrato"
    },
    "status": "Bad Request",
    "code": 400
}

**Comment by AlessioBazzanella** [comment]
Nel caso in cui la password sia sbagliata:

{
    "data": {
        "message": "Password sbagliata"
    },
    "status": "Bad Request",
    "code": 400
}
